# Generated by Django 2.2.7 on 2019-11-28 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equiv_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_user', to=settings.AUTH_USER_MODEL, verbose_name='related internal user object')),
            ],
        ),
    ]
